### ISSUE TITLE
Systematic Multiprocessing (SMP) support

### ISSUE THREAD

**Issue by 1byte2bytes** [1byte2bytes/SydOS#42]
https://wiki.osdev.org/Symmetric_Multiprocessing

**Comment by 1byte2bytes** [comment]
Blocked by #43

**Comment by Goldfish64** [comment]
One of the requirements for SMP, the I/O APIC, is now implemented.

**Comment by Goldfish64** [comment]
SMP is now partially implemented, with the OS discovering and initializing additional processors, changing into protected mode, enabling paging, etc.

**Comment by Goldfish64** [comment]
Closing this as additional updates will be done in #30, as SMP support for multitasking requires revamping the multitasking system anyway.
